### ISSUE TITLE
Refine Setup and Contribution Guidelines for Better Clarity

### ISSUE THREAD

**Issue by ginSpirit** [Md-Dipu/learning-parcel-and-workflow#19]
Issue Description:

The current documentation for project setup and contributing can be improved. Suggestions:

    Installation: Add detailed setup steps for different operating systems and troubleshooting for Git/SSH key issues.
    Contributing Include steps for running the project locally, testing changes, and ensuring code consistency.

These updates will make the onboarding process smoother for new contributors.

**Comment by Md-Dipu** [comment]
Documentation has been improved.
